language: node_js
sudo: false
node_js:
- 10
- 12
cache:
  npm: false
before_install:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ ! -z ${encrypted_key} ] &&
    openssl aes-256-cbc -K $encrypted_key
    -iv $encrypted_iv -in secrets.js.enc -out test/resources/secrets.js
    -d || true'
script:
- npm run build
- npm run test-unit-travis || travis_terminate 1
- npm run test-integration-travis || travis_terminate 1
- npm run check-packages
after_success:
- npm run report-coverage
deploy:
- provider: script
  skip_cleanup: true
  script: npx semantic-release
  on:
    node: 12
    repo: ibm-cloud-security/security-advisor-sdk-node
